FROM node:21-alpine3.18 as builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools

RUN npm install -g npm@latest
RUN ls -a

# Ensure that the NPM_TOKEN is available as an environment variable
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}

# Install dependencies and global packages
RUN npm install && npm install -g nodemon

EXPOSE 4001

CMD ["npm", "run", "dev"]
